# Generated by Django 3.2.5 on 2021-07-24 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_memoryfragment_fragment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fragment',
            name='updatedAt',
        ),
    ]
