# Generated by Django 3.2.5 on 2021-07-25 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_blacklistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistentry',
            name='pinyin',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
