# Generated by Django 3.2.5 on 2021-07-25 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_blacklistentry_pinyin'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklistentry',
            name='english',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='blacklistentry',
            name='reason',
            field=models.CharField(default='', max_length=250),
        ),
    ]
