# Generated by Django 3.2.5 on 2021-07-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_fragment_updatedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='priority',
            field=models.IntegerField(default=999),
        ),
    ]
