# Generated by Django 4.0.3 on 2024-03-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_entry_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('custom', 'Custom'), ('priority', 'Priority'), ('blacklist', 'Blacklist'), ('other', 'Other')], max_length=10)),
                ('owner', models.CharField(default='', max_length=50)),
                ('traditional', models.CharField(default='', max_length=20)),
                ('simplified', models.CharField(max_length=20)),
                ('pinyin', models.CharField(max_length=100)),
                ('english', models.CharField(max_length=200)),
                ('reason', models.CharField(default='', max_length=1000)),
                ('notes', models.CharField(default='', max_length=1000)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('priority', models.IntegerField(default=1111)),
            ],
        ),
    ]
